# __init__.py

"""Agent orchestration: parse helpers, Ollama client, state, prompts, and graph."""

from src.agent.json_output import (
    FAIL,
    FIRST_PARSE_FAILURE,
    RETRY_STRICT,
    STRICT_RETRY_INSTRUCTION,
    JsonOutputError,
    JsonParseError,
    JsonSchemaError,
    decide_after_parse_failure,
    parse_json_output,
    strip_markdown_fences,
)
from src.agent.confirm_sources import (
    ACTION_ABORT,
    ACTION_CONFIRM,
    ACTION_SELECT,
    KIND_CONFIRM_SOURCES,
    apply_confirm_decision,
    build_interrupt_payload,
    decide_confirm_reason,
)
from src.agent.profile_steps import (
    ACTION_CONTINUE,
    ACTION_SKIP_REMAINING,
    KIND_PROFILE_STEP,
    apply_profile_decision,
    build_profile_interrupt,
    should_pause_profiling,
)
from src.agent.code_approval import (
    ACTION_APPROVE,
    ACTION_EDIT_RUN,
    ACTION_REJECT,
    KIND_APPROVE_CODE,
    apply_code_decision,
    build_code_interrupt,
    should_pause_generated_code,
)
from src.agent.codegen import (
    KIND_PYTHON,
    KIND_SQL,
    CodegenError,
    generate_checked_code,
)
from src.agent.execute import (
    ToolValidationError,
    interpret_model_reply,
    parse_tool_call,
    retry_prompt_after_validation,
    run_allowlisted_tool,
    validate_tool_call,
)
from src.agent.graph import CompleteFn, build_graph, build_prompt
from src.agent.llm import (
    ROLE_AGENTIC,
    ROLE_CODING,
    ROLE_FALLBACK_FAST,
    ROLE_PRIMARY,
    LlmError,
    complete,
    model_for_role,
)
from src.agent.prompts import build_system_prompt
from src.agent.state import (
    ALLOWED_HITL_MODES,
    HITL_MODE_AUTO,
    HITL_MODE_GUIDED,
    HITL_MODE_STANDARD,
    AgentMessage,
    AgentState,
    as_artifact_path,
    empty_agent_state,
)

__all__ = [
    "FAIL",
    "FIRST_PARSE_FAILURE",
    "RETRY_STRICT",
    "STRICT_RETRY_INSTRUCTION",
    "JsonOutputError",
    "JsonParseError",
    "JsonSchemaError",
    "decide_after_parse_failure",
    "parse_json_output",
    "strip_markdown_fences",
    "ROLE_AGENTIC",
    "ROLE_CODING",
    "ROLE_FALLBACK_FAST",
    "ROLE_PRIMARY",
    "LlmError",
    "complete",
    "model_for_role",
    "ALLOWED_HITL_MODES",
    "HITL_MODE_AUTO",
    "HITL_MODE_GUIDED",
    "HITL_MODE_STANDARD",
    "AgentMessage",
    "AgentState",
    "as_artifact_path",
    "empty_agent_state",
    "build_system_prompt",
    "CompleteFn",
    "ACTION_ABORT",
    "ACTION_CONFIRM",
    "ACTION_CONTINUE",
    "ACTION_SELECT",
    "ACTION_SKIP_REMAINING",
    "KIND_APPROVE_CODE",
    "KIND_CONFIRM_SOURCES",
    "KIND_PROFILE_STEP",
    "ACTION_APPROVE",
    "ACTION_EDIT_RUN",
    "ACTION_REJECT",
    "apply_code_decision",
    "apply_confirm_decision",
    "apply_profile_decision",
    "build_code_interrupt",
    "should_pause_generated_code",
    "build_interrupt_payload",
    "build_profile_interrupt",
    "decide_confirm_reason",
    "should_pause_profiling",
    "build_graph",
    "build_prompt",
    "KIND_PYTHON",
    "KIND_SQL",
    "CodegenError",
    "generate_checked_code",
    "ToolValidationError",
    "interpret_model_reply",
    "parse_tool_call",
    "retry_prompt_after_validation",
    "run_allowlisted_tool",
    "validate_tool_call",
]
